Genetic Algorithms for Solving the Traveling Salesman Problem

In [1]:
import random
import numpy as np

In [2]:
# Define the cities and their coordinates
cities = {
    'A': (0, 0),
    'B': (1, 2),
    'C': (3, 1),
    'D': (4, 3),
    'E': (2, 1)
}

In [3]:
# Create a distance matrix
def calculate_distance(city1, city2):
    return np.linalg.norm(np.array(city1) - np.array(city2)) #Euclidean distance

In [4]:
num_cities = len(cities)
dist_matrix = np.zeros((num_cities, num_cities)) #new array filled with zeros.
city_names = list(cities.keys())

In [5]:
for i in range(num_cities):
    for j in range(num_cities):
        dist_matrix[i][j] = calculate_distance(cities[city_names[i]], cities[city_names[j]])

#print(dist_matrix)

[[0.         2.23606798 3.16227766 5.         2.23606798]
 [2.23606798 0.         2.23606798 3.16227766 1.41421356]
 [3.16227766 2.23606798 0.         2.23606798 1.        ]
 [5.         3.16227766 2.23606798 0.         2.82842712]
 [2.23606798 1.41421356 1.         2.82842712 0.        ]]


In [6]:
# Genetic Algorithm Parameters
POPULATION_SIZE = 10
NUM_GENERATIONS = 100
MUTATION_RATE = 0.01

In [7]:
# Initialize population
def create_individual():
    return random.sample(city_names, len(city_names))

population = [create_individual() for _ in range(POPULATION_SIZE)]
#print(population)

[['C', 'A', 'D', 'E', 'B'], ['A', 'E', 'C', 'B', 'D'], ['E', 'B', 'A', 'C', 'D'], ['D', 'E', 'A', 'C', 'B'], ['C', 'A', 'B', 'D', 'E'], ['C', 'B', 'A', 'E', 'D'], ['D', 'E', 'C', 'B', 'A'], ['A', 'E', 'C', 'D', 'B'], ['B', 'D', 'E', 'A', 'C'], ['D', 'B', 'A', 'C', 'E']]


In [8]:
# Fitness function (total distance of the route)
def calculate_fitness(individual):
    total_distance = 0
    for i in range(num_cities - 1):
        total_distance += dist_matrix[city_names.index(individual[i])][city_names.index(individual[i+1])]
    total_distance += dist_matrix[city_names.index(individual[-1])][city_names.index(individual[0])]
    return 1 / total_distance  # We want to maximize fitness

In [9]:
# Selection (roulette wheel selection)
def selection(population, fitness_scores):
    return random.choices(population, weights=fitness_scores, k=2) 

In [10]:
# Crossover (ordered crossover)
def crossover(parent1, parent2):
    child = [None] * len(parent1)
    start, end = sorted(random.sample(range(len(parent1)), 2))
    child[start:end] = parent1[start:end]
    remaining = [item for item in parent2 if item not in child]
    child[:start] = [item for item in remaining[:start] if item not in child]
    child[end:] = [item for item in remaining[start:] if item not in child]
    return child

In [11]:
# Mutation (swap mutation)
def mutation(individual):
    if random.random() < MUTATION_RATE:
        idx1, idx2 = random.sample(range(len(individual)), 2)
        individual[idx1], individual[idx2] = individual[idx2], individual[idx1]
    return individual

In [12]:
# Genetic Algorithm main loop
for generation in range(NUM_GENERATIONS):
    # Calculate fitness for each individual
    fitness_scores = [calculate_fitness(individual) for individual in population]

    # Select parents
    new_population = []
    for _ in range(int(POPULATION_SIZE / 2)):
        parent1, parent2 = selection(population, fitness_scores)
        child1 = crossover(parent1, parent2)
        child2 = crossover(parent2, parent1)
        new_population.extend([mutation(child1), mutation(child2)])

    # Replace old population with new population
    population = new_population

In [13]:
# Get the best individual from the final population
best_individual = max(population, key=calculate_fitness)
best_distance = sum(dist_matrix[city_names.index(best_individual[i])][city_names.index(best_individual[i+1])] for i in range(num_cities - 1))
best_distance += dist_matrix[city_names.index(best_individual[-1])][city_names.index(best_individual[0])]

In [14]:
print("Best Route:", best_individual)
print("Best Distance:", best_distance)

Best Route: ['C', 'D', 'E', 'B', 'A']
Best Distance: 11.877054302287243


In [15]:
import random
import numpy as np

# Define the cities and their coordinates
cities = {
    'A': (0, 0),
    'B': (1, 3),
    'C': (4, 2),
    'D': (5, 0),
    'E': (2, 1)
}

# Create a distance matrix
def calculate_distance(city1, city2):
    return np.linalg.norm(np.array(city1) - np.array(city2))

num_cities = len(cities)
dist_matrix = np.zeros((num_cities, num_cities))
city_names = list(cities.keys())

for i in range(num_cities):
    for j in range(num_cities):
        dist_matrix[i][j] = calculate_distance(cities[city_names[i]], cities[city_names[j]])

# Genetic Algorithm Parameters
POPULATION_SIZE = 100
NUM_GENERATIONS = 500
MUTATION_RATE = 0.01

# Initialize population
def create_individual():
    return random.sample(city_names, len(city_names))

population = [create_individual() for _ in range(POPULATION_SIZE)]

# Fitness function (total distance of the route)
def calculate_fitness(individual):
    total_distance = 0
    for i in range(num_cities - 1):
        total_distance += dist_matrix[city_names.index(individual[i])][city_names.index(individual[i+1])]
    total_distance += dist_matrix[city_names.index(individual[-1])][city_names.index(individual[0])]
    return 1 / total_distance  # We want to maximize fitness

# Selection (roulette wheel selection)
def selection(population, fitness_scores):
    return random.choices(population, weights=fitness_scores, k=2)

# Crossover (ordered crossover)
def crossover(parent1, parent2):
    child = [None] * len(parent1)
    start, end = sorted(random.sample(range(len(parent1)), 2))
    child[start:end] = parent1[start:end]
    remaining = [item for item in parent2 if item not in child]
    child[:start] = [item for item in remaining[:start] if item not in child]
    child[end:] = [item for item in remaining[start:] if item not in child]
    return child

# Mutation (swap mutation)
def mutation(individual):
    if random.random() < MUTATION_RATE:
        idx1, idx2 = random.sample(range(len(individual)), 2)
        individual[idx1], individual[idx2] = individual[idx2], individual[idx1]
    return individual

# Genetic Algorithm main loop
for generation in range(NUM_GENERATIONS):
    # Calculate fitness for each individual
    fitness_scores = [calculate_fitness(individual) for individual in population]

    # Select parents
    new_population = []
    for _ in range(int(POPULATION_SIZE / 2)):
        parent1, parent2 = selection(population, fitness_scores)
        child1 = crossover(parent1, parent2)
        child2 = crossover(parent2, parent1)
        new_population.extend([mutation(child1), mutation(child2)])

    # Replace old population with new population
    population = new_population

# Get the best individual from the final population
best_individual = max(population, key=calculate_fitness)
best_distance = sum(dist_matrix[city_names.index(best_individual[i])][city_names.index(best_individual[i+1])] for i in range(num_cities - 1))
best_distance += dist_matrix[city_names.index(best_individual[-1])][city_names.index(best_individual[0])]

print("Best Route:", best_individual)
print("Best Distance:", best_distance)


Best Route: ['C', 'D', 'E', 'A', 'B']
Best Distance: 13.95896893550472
